version: '3.8'
services:
  frontend_reactjs_yt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8989:80'
    volumes:
      - .:/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
